# Generated by Django 5.2 on 2025-05-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        unique=True,
                        verbose_name="Identificação do produto",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Descrição detalhada do produto"),
                ),
                (
                    "ncm_code",
                    models.CharField(max_length=16, verbose_name="Código NCM"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Preço unitário do produto",
                    ),
                ),
            ],
        ),
    ]
