# Generated by Django 5.2 on 2025-05-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Taxes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=128)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "scope",
                    models.CharField(
                        choices=[("ESTADUAL", "Estadual"), ("FEDERAL", "Federal")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
