# Generated by Django 5.2 on 2025-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxes",
            name="taxa_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="taxes",
            name="scope",
            field=models.CharField(
                choices=[
                    ("ESTADUAL", "Estadual"),
                    ("FEDERAL", "Federal"),
                    ("TAXA", "Taxa"),
                ],
                max_length=10,
            ),
        ),
    ]
