# Generated by Django 5.2 on 2025-05-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0002_taxes_taxa_amount_alter_taxes_scope"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxes",
            name="taxa_amount",
        ),
        migrations.AddField(
            model_name="taxes",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Valor da Taxa quase não seja calculado pela porcentagem",
            ),
        ),
        migrations.AlterField(
            model_name="taxes",
            name="description",
            field=models.CharField(max_length=128, verbose_name="Descrição do Imposto"),
        ),
        migrations.AlterField(
            model_name="taxes",
            name="percentage",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Porcentagem do impostos"
            ),
        ),
        migrations.AlterField(
            model_name="taxes",
            name="scope",
            field=models.CharField(
                choices=[
                    ("ESTADUAL", "Estadual"),
                    ("FEDERAL", "Federal"),
                    ("TAXA", "Taxa"),
                ],
                max_length=10,
                verbose_name="Escopo do imposto: Estadual, Federal ou Taxa",
            ),
        ),
    ]
