from django.contrib import admin
from django.urls import path
from products.views import (
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
    ProductUpdateView,
)
from quotations.views import (
    QuotationCreateView,
    QuotationItemDeleteView,
    QuotationListView,
    QuotationUpdateView,
)
from taxes.views import (
    TaxCreateView,
    TaxDeleteView,
    TaxDetailView,
    TaxListView,
    TaxUpdateView,
)

from .views import HomeView

urlpatterns = [
    path(
        "",
        HomeView.as_view(),
        name="home",
    ),
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "products",
        ProductListView.as_view(),
        name="product-list",
    ),
    path(
        "products/create/",
        ProductCreateView.as_view(),
        name="product-create",
    ),
    path(
        "products/<int:pk>/",
        ProductDetailView.as_view(),
        name="product-detail",
    ),
    path(
        "products/<int:pk>/update/",
        ProductUpdateView.as_view(),
        name="product-update",
    ),
    path(
        "products/<int:pk>/delete/",
        ProductDeleteView.as_view(),
        name="product-delete",
    ),
    path(
        "taxes/",
        TaxListView.as_view(),
        name="tax-list",
    ),
    path(
        "taxes/create/",
        TaxCreateView.as_view(),
        name="tax-create",
    ),
    path(
        "taxes/<int:pk>/",
        TaxDetailView.as_view(),
        name="tax-detail",
    ),
    path(
        "taxes/<int:pk>/edit/",
        TaxUpdateView.as_view(),
        name="tax-edit",
    ),
    path(
        "taxes/<int:pk>/delete/",
        TaxDeleteView.as_view(),
        name="tax-delete",
    ),
    path(
        "quotations/",
        QuotationListView.as_view(),
        name="quotation-list",
    ),
    path(
        "quotations/create/",
        QuotationCreateView.as_view(),
        name="quotation-create",
    ),
    path(
        "quotations/<int:pk>/edit/",
        QuotationUpdateView.as_view(),
        name="quotation-edit",
    ),
    path(
        "quotation/item/<int:pk>/delete/",
        QuotationItemDeleteView.as_view(),
        name="quotation-item-delete",
    ),
]
